# Generated by Django 3.2.25 on 2025-10-31 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20251031_1204'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='commenting_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacher', verbose_name='コメント記入教員'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='teacher_comment',
            field=models.TextField(blank=True, null=True, verbose_name='教員からのコメント'),
        ),
    ]
