# Generated by Django 3.2.25 on 2025-11-18 02:46

from django.db import migrations, models
import portfolios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20251031_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'ポートフォリオ（表紙）', 'verbose_name_plural': 'ポートフォリオ（表紙）'},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'verbose_name': 'ポートフォリオ作品', 'verbose_name_plural': 'ポートフォリオ作品'},
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='file',
            field=models.FileField(help_text='PDF, 画像(JPG/PNG), またはソースコード一式(ZIP)をアップロードしてください。', upload_to='portfolio_files/', validators=[portfolios.validators.validate_file_extension], verbose_name='成果物ファイル'),
        ),
    ]
