# Generated by Django 3.2.25 on 2026-01-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20251118_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='AIフィードバック'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='AI点数'),
        ),
    ]
