# Generated by Django 3.2.25 on 2026-01-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_auto_20260126_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='ai_feedback',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='ai_score',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='AIフィードバック'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='AI点数'),
        ),
    ]
