# Generated by Django 3.2.25 on 2026-02-05 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_auto_20260126_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(300)], verbose_name='説明文'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=30, verbose_name='タイトル'),
        ),
    ]
