# Generated by Django 3.2.25 on 2025-11-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'お知らせ', 'verbose_name_plural': 'お知らせ一覧'},
        ),
    ]
