# Generated by Django 3.2.25 on 2025-11-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'タグ', 'verbose_name_plural': 'タグ一覧'},
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('strength', '強み・スキル'), ('condition', '条件・待遇'), ('both', 'その他・両方')], default='both', max_length=20, verbose_name='カテゴリー'),
        ),
    ]
