# Generated by Django 3.2.25 on 2026-02-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20251120_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('subject', models.CharField(max_length=200, verbose_name='件名')),
                ('message', models.TextField(verbose_name='お問い合わせ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日')),
            ],
        ),
    ]
