# Generated by Django 3.2.25 on 2026-02-05 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'お問い合わせ', 'verbose_name_plural': 'お問い合わせ'},
        ),
    ]
