# Generated by Django 3.2.25 on 2026-02-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_inquiry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='企業名')),
                ('contact_name', models.CharField(max_length=100, verbose_name='担当者名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(max_length=20, verbose_name='電話番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申込日')),
            ],
            options={
                'verbose_name': '企業申し込み',
                'verbose_name_plural': '企業申し込み一覧',
            },
        ),
        migrations.CreateModel(
            name='SchoolApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, verbose_name='学校名')),
                ('contact_name', models.CharField(max_length=100, verbose_name='担当者名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(max_length=20, verbose_name='電話番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申込日')),
            ],
            options={
                'verbose_name': '学校申し込み',
                'verbose_name_plural': '学校申し込み一覧',
            },
        ),
    ]
