# Generated by Django 3.2.25 on 2025-11-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'チャットメッセージ', 'verbose_name_plural': 'チャットメッセージ'},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'チャットルーム', 'verbose_name_plural': 'チャットルーム'},
        ),
    ]
