# Generated by Django 3.2.25 on 2025-10-31 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_favoritecompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生一覧'},
        ),
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='教員からのコメント'),
        ),
        migrations.AddField(
            model_name='student',
            name='comment_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacher', verbose_name='コメント記入教員'),
        ),
    ]
