# Generated by Django 3.2.25 on 2025-11-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20251031_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_public_to_companies',
            field=models.BooleanField(default=True, verbose_name='企業へのプロフィール公開'),
        ),
    ]
