# Generated by Django 3.2.25 on 2025-11-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_is_public_to_companies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyrepresentative',
            options={'verbose_name': '企業担当者', 'verbose_name_plural': '企業担当者'},
        ),
        migrations.AlterModelOptions(
            name='favoritecompany',
            options={'verbose_name': 'お気に入り企業', 'verbose_name_plural': 'お気に入り企業一覧'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生プロフィール', 'verbose_name_plural': '学生プロフィール'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教員プロフィール', 'verbose_name_plural': '教員プロフィール'},
        ),
    ]
