# Generated by Django 3.2.25 on 2025-12-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studenttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')], default=1, verbose_name='学年'),
        ),
    ]
