# Generated by Django 3.2.25 on 2025-12-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrepresentative',
            name='job_offer_url',
            field=models.URLField(blank=True, help_text='部署ごとの採用ページや求人票のリンクがあれば入力してください', null=True, verbose_name='求人票URL'),
        ),
    ]
