# Generated by Django 3.2.25 on 2025-12-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_companyrepresentative_job_offer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrepresentative',
            name='job_offer_pdf',
            field=models.FileField(blank=True, help_text='PDF形式の求人票をアップロードできます', null=True, upload_to='job_offers/', verbose_name='求人票PDF'),
        ),
    ]
