# Generated by Django 4.2.25 on 2025-10-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='企業名')),
                ('industry', models.CharField(max_length=100, verbose_name='業種')),
                ('description', models.TextField(verbose_name='事業内容')),
            ],
        ),
    ]
