# Generated by Django 3.2.25 on 2025-11-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_scout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '企業', 'verbose_name_plural': '企業一覧'},
        ),
        migrations.AlterModelOptions(
            name='scout',
            options={'verbose_name': 'スカウト', 'verbose_name_plural': 'スカウト一覧'},
        ),
    ]
