# Generated by Django 3.2.25 on 2025-11-19 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag'),
        ('companies', '0003_auto_20251118_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('strength', '求める人材の強み'), ('feature', '自社の特徴・政策')], max_length=10)),
                ('rank', models.IntegerField(choices=[(1, '1位'), (2, '2位'), (3, '3位'), (4, '4位'), (5, '5位')], verbose_name='順位')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='companies.company')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
            ],
            options={
                'ordering': ['tag_type', 'rank'],
                'unique_together': {('company', 'tag_type', 'rank')},
            },
        ),
    ]
