# Generated by Django 3.2.25 on 2025-12-31 14:23

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companytag'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(default=companies.models.generate_company_code, editable=False, max_length=8, unique=True, verbose_name='企業コード'),
        ),
    ]
