# Generated by Django 3.2.25 on 2025-12-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='企業ホームページ'),
        ),
    ]
