# Generated by Django 3.2.25 on 2026-01-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_website_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scout',
            options={'ordering': ['-created_at'], 'verbose_name': 'スカウト', 'verbose_name_plural': 'スカウト一覧'},
        ),
        migrations.AddField(
            model_name='scout',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='既読フラグ'),
        ),
        migrations.AddField(
            model_name='scout',
            name='message',
            field=models.TextField(default='あなたのポートフォリオを見てスカウトしました！', verbose_name='スカウトメッセージ'),
        ),
    ]
