# Generated by Django 4.2.25 on 2025-10-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学校名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
            ],
        ),
    ]
