# Generated by Django 3.2.25 on 2025-11-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '学校', 'verbose_name_plural': '学校一覧'},
        ),
    ]
