# Generated by Django 3.2.25 on 2025-12-31 14:08

from django.db import migrations, models
import schools.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(default=schools.models.generate_school_code, editable=False, max_length=8, unique=True, verbose_name='学校コード'),
        ),
    ]
